export const employeesData = [
    {
      employeeID: "821092",
      firstName: "Rajinikanth",
      lastName: "Reddy",
      email: "raj.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Male",
      contact: "8300199102",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "rajinikanth@gmail.com",
    },
    {
      employeeID: "912092",
      firstName: "Prasanth",
      lastName: "Reddy",
      email: "prasanth.@gmail.com",
      designation: "Full",
      dob: "12-03-1998",
      gender: "Male",
      contact: "8897403689",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "prasanth@gmail.com",
    },
    {
      employeeID: "247094",
      firstName: "Sara",
      lastName: "Khan",
      email: "sara.@gmail.com",
      designation: "ios",
      dob: "12-03-1993",
      gender: "Female",
      contact: "9022887782",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "sara@gmail.com",
    },
    {
      employeeID: "321092",
      firstName: "John",
      lastName: "Doe",
      email: "john.@gmail.com",
      designation: "Full",
      dob: "09-06-1997",
      gender: "Male",
      contact: "7642789293",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "john@gmail.com",
    },
    {
      employeeID: "702028",
      firstName: "Priya",
      lastName: "Raj",
      email: "priya.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Female",
      contact: "8300199102",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "priya@gmail.com",
    },
    {
      employeeID: "731092",
      firstName: "Ankit",
      lastName: "Verma",
      email: "ankit.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Male",
      contact: "99678490298",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "Ankit@gmail.com",
    },
    {
      employeeID: "421092",
      firstName: "Neha",
      lastName: "Singh",
      email: "neha.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Female",
      contact: "8798199102",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "Neha@gmail.com",
    },
    {
      employeeID: "721092",
      firstName: "Ravi",
      lastName: "Patel",
      email: "ravi.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Male",
      contact: "99678490298",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "ravi@gmail.com",
    },
    {
      firstName: "Sneha",
      lastName: "Mishra",
      email: "sneha.@gmail.com",
      designation: "Testing",
      dob: "12-03-1999",
      gender: "Female",
      contact: "9087434363",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "sneha@gmail.com",
    },
    {
      employeeID: "211092",
      firstName: "Kiran",
      lastName: "Rao",
      email: "kiran.@gmail.com",
      designation: "Full",
      dob: "12-03-1999",
      gender: "Male",
      contact: "89987622221",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "kiran@gmail.com",
    },
    {
      employeeID: "802028",
      firstName: "Dev",
      lastName: "Singh",
      email: "dev.@gmail.com",
      designation: "Full",
      dob: "12-03-2002",
      gender: "Male",
      contact: "8300199102",
      emergencyContact: "Enter Emergency Contact",
      reportingmanager: "Vishal",
      department: "Development",
      role: "Employee",
      doj: "02-05-2025",
      hr: "Divya",
      promotiondate: "dd-mm-yyyy",
      resignation: "dd-mm-yyyy",
      lastworking: "dd-mm-yyyy",
      companyemail: "dev@gmail.com",
    },
  ];