export  const quotes =  [
    { text: "Keep Smiling", author: "Rajinikanth" },
    { text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Success is not final; failure is not fatal.", author: "Winston Churchill" },
    { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "Keep Smiling", author: "Rajinikanth" },
    { text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Success is not final; failure is not fatal.", author: "Winston Churchill" },
    { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "Keep Smiling", author: "Rajinikanth" },
    { text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Success is not final; failure is not fatal.", author: "Winston Churchill" },
    { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    
  ];